# Generated by Django 2.1.7 on 2019-11-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='current_circle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='surplus',
            field=models.BooleanField(default=True),
        ),
    ]
