# Generated by Django 2.1.7 on 2019-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20191123_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='repition',
            field=models.BooleanField(null=True),
        ),
    ]
