# Generated by Django 2.1.7 on 2019-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20191123_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='current_circle',
            field=models.IntegerField(default=0),
        ),
    ]
