# Generated by Django 2.1.7 on 2019-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deficit',
            field=models.BooleanField(default=False),
        ),
    ]
