# Generated by Django 2.1.7 on 2019-12-02 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20191127_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deficit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Category'),
        ),
    ]
