# Generated by Django 2.1.7 on 2019-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20191202_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deficit',
            field=models.BooleanField(default=False),
        ),
    ]
